# Q.2) 2D NumPy array operations

In [1]:
import numpy as np

arr = np.random.randint(1, 101, (10, 5))
print("Array:")
print(arr)

print(f"\nSum of odd numbers: {np.sum(arr[arr % 2 != 0])}")
print(f"Sum of even numbers: {np.sum(arr[arr % 2 == 0])}")
print(f"Sum of diagonal elements: {np.sum(np.diag(arr[:5, :5]))}")
print(f"\nTranspose:\n{arr.T}")
print(f"\nRows 2-6:\n{arr[1:6]}")

arr_modified = arr.copy()
arr_modified[1:6] *= -1
print(f"\nAfter multiplying rows 2-6 by -1:\n{arr_modified}")

flattened = arr[1:6].flatten()
print(f"\nFlattened rows 2-6: {flattened}")

print(f"Sum of all elements: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Standard Deviation: {np.std(arr)}")

sorted_flat = np.sort(arr.flatten())
print(f"Flattened and sorted: {sorted_flat}")

Array:
[[ 96   2  59  23  26]
 [ 69  67   2  30 100]
 [ 45  75  39  34  75]
 [ 61  87  25  75  75]
 [ 40   6  42  10  41]
 [  8  88  64  38  78]
 [ 16  15  44  72  28]
 [  4  66  98  24  79]
 [ 55  82  34  72  99]
 [ 57  40  21  87  43]]

Sum of odd numbers: 1272
Sum of even numbers: 1244
Sum of diagonal elements: 318

Transpose:
[[ 96  69  45  61  40   8  16   4  55  57]
 [  2  67  75  87   6  88  15  66  82  40]
 [ 59   2  39  25  42  64  44  98  34  21]
 [ 23  30  34  75  10  38  72  24  72  87]
 [ 26 100  75  75  41  78  28  79  99  43]]

Rows 2-6:
[[ 69  67   2  30 100]
 [ 45  75  39  34  75]
 [ 61  87  25  75  75]
 [ 40   6  42  10  41]
 [  8  88  64  38  78]]

After multiplying rows 2-6 by -1:
[[  96    2   59   23   26]
 [ -69  -67   -2  -30 -100]
 [ -45  -75  -39  -34  -75]
 [ -61  -87  -25  -75  -75]
 [ -40   -6  -42  -10  -41]
 [  -8  -88  -64  -38  -78]
 [  16   15   44   72   28]
 [   4   66   98   24   79]
 [  55   82   34   72   99]
 [  57   40   21   87   43]]

Flattene